---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/antigenius0910/concourse-tutorial.git
      branch: master

  - name: resource-app
    type: git
    source:
      uri: https://github.com/antigenius0910/simple-go-web-app.git

  - name: resource-zabbix
    type: git
    source:
      uri: https://github.com/antigenius0910/zabbix.git
      branch: release/4.0_yen

jobs:
  - name: job-test-app
    public: true
    plan:
      - get: resource-tutorial
      - get: resource-app
        trigger: true
      - get: resource-zabbix
      - task: web-app-tests
        file: resource-zabbix/hack/ci/task_run_tests.yml
